# documentation at https://starship.rs/config

[character]
success_symbol = "âœ"
error_symbol = "âœ—"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "Ğ¾Ñ‚Ğ½Ğµ [$duration]($style) "
show_notifications = true

[directory]
home_symbol = "ğŸ "

[battery]
disabled = true