# documentation at https://starship.rs/config

[character]
symbol = "➜"
error_symbol = "✗"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "отне [$duration]($style) "
show_notifications = true