[".config/zellij/plugins/harpoon.wasm"]
    type = "file"
    url = "https://github.com/Nacho114/harpoon/releases/download/v0.1.0/harpoon.wasm"
    checksum.sha256 = "cad9f87da31ddbaabb9b36c4d6820d33fbbad925e88f16b06bddb82bdf009602"
