[".config/zellij/plugins/harpoon.wasm"]
    type = "file"
    url = "https://github.com/Nacho114/harpoon/releases/download/v0.2.0/harpoon.wasm"
    checksum.sha256 = "27acf80aebd1dfba2a7c6f87ea96f6fa4d3ebaa60430792e9b2b83e47cd91e3c"
